<?php
/**
 * @var Zend\View\Renderer\PhpRenderer         $this
 * @var \Application\ResultSet\SupportedLocale $supportedLocales
 * @var \Application\ResultSet\Translation     $translations
 * @var \Application\ResultSet\TranslationBase $translationBase
 * @var \Application\ResultSet\TranslationFile $translationFiles
 * @var \Application\Model\SupportedLocale     $locale
 */
?>
<h2><?= $this->translate('Import') ?></h2>
<div class="card mt-4">
    <div class="card-header">Import CSV files (Dummy, not yet implemented!)</div>
    <div class="card-body">

        <form action="<?php echo $this->url('admin', [ 'action' => 'import' ]) ?>" method="post" multipart="" enctype="multipart/form-data" role="form">
            <div class="form-group">
                <label class="control-label" for="filebutton">Select File(s)</label><br>
                <input type="file" name="img[]" id="files" class="input-large" multiple>
            </div>
            <div class="form-group row">
                <div class="col-sm-2">
                    <label for="language">Import as language</label>
                    <select class="form-control">
                        <?php foreach ($supportedLocales as $locale): ?>
                            <option value="<?php echo $locale->getId() ?>"><?php echo $locale->getLocale() ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <button type="submit" id="submit" name="Import" class="btn btn-success button-loading" data-loading-text="Loading...">Start Import</button>
            </div>
        </form>
    </div>
</div>
