<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Import\Form\ImportForm         $form
 */

$title = $this->translate('Import magento language CSV file(s)');
$this->headTitle($title);

$form = $this->form;
$form->setAttribute('action', $this->url('import', [ 'action' => 'index' ]));
$form->prepare();
?>

<div class="card mt-4">
    <div class="card-header">
        <?= $this->escapeHtml($title); ?>
    </div>
    <div class="card-body">
        <?= $this->form()->openTag($form); ?>
            <div class="form-group">
                <?php $files = $form->get('files'); ?>
                <?= $this->formLabel($files); ?>
                <?= $this->formElement($files); ?>
                <?= $this->formElementErrors($files); ?>
            </div>
            <div class="form-group">
                <?php $locale = $form->get('locale'); ?>
                <?= $this->formLabel($locale); ?>
                <?= $this->formElement($locale); ?>
                <?= $this->formElementErrors($locale); ?>
            </div>
            <div class="form-group">
                <?= $this->formElement($form->get('submit')); ?>
            </div>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>

<?php $this->inlineScript()->captureStart(); ?>

/*
$("document").ready(function () {
    $("#filebutton").change(function () {
        var fullPath   = $("#filebutton").val();

        if (fullPath) {
            var startIndex = (fullPath.indexOf('\\') >= 0 ? fullPath.lastIndexOf('\\') : fullPath.lastIndexOf('/'));
            var filename   = fullPath.substring(startIndex);

            if ((filename.indexOf('\\') === 0) || (filename.indexOf('/') === 0)) {
                filename = filename.substring(1);
            }

            // Remove file extension
            filename = filename.substring(0, filename.lastIndexOf(".csv"));

            // Extract locale from file name
            var tokens = filename.split('_').slice(-2);
            var locale = tokens.join('_');

            // Pre select locale
            $("#locale").val(locale);
        }
    });
});
*/

<?php $this->inlineScript()->captureEnd(); ?>
