<?php
$title = 'Add new locale';
$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title); ?></h1>

<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('locale', [ 'action' => 'add' ]));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
    echo $this->formRow($form->get('locale'));
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
?>
