<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 */

$title = $this->translate('Delete locale');
$this->headTitle($title);

$url = $this->url('locale', [ 'action' => 'delete', 'id' => $this->id ]);
?>

<div class="card mt-4">
    <div class="card-header">
        <p>Are you sure that you want to delete '<?= $this->escapeHtml($locale->getLocale()); ?>'?</p>
    </div>
    <div class="card-body">
        <form action="<?= $url; ?>" method="post">
            <div class="form-group">
                <input type="hidden" name="id" value="<?= $locale->getId(); ?>" />
            </div>
            <div class="form-group">
                <input class="btn btn-danger" type="submit" name="del" value="Yes" />
                <input class="btn btn-success" type="submit" name="del" value="No" />
            </div>
        </form>
    </div>
</div>
