<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 */

$title = $this->translate('Delete locale');
$this->headTitle($title);

$url = $this->url('locale', [ 'action' => 'delete', 'id' => $this->id ]);
?>

<div class="card mt-4">
    <div class="card-header">
        <p><?= sprintf($this->translate('Are you sure that you want to delete "%s"?'), $this->escapeHtml($locale->getLocale())) ?></p>
    </div>
    <div class="card-body">
        <form action="<?= $url; ?>" method="post">
            <div class="form-group">
                <input type="hidden" name="id" value="<?= $locale->getId(); ?>" />
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit" name="del" value="Yes" >
                    <i class="fa fa-check-circle"></i><span class="ml-2"><?= $this->translate('Yes') ?></span>
                </button>
                <button class="btn btn-success" type="submit" name="del" value="No" >
                    <i class="fa fa-times-circle"></i><span class="ml-2"><?= $this->translate('No') ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
