<?php
$title = 'Delete locale';
$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete '<?= $this->escapeHtml($locale->getLocale()); ?>'?</p>
<?php

$url = $this->url('locale', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>

<form action="<?= $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?= $locale->getId(); ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>