<?php
$title = 'Edit locale';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('locale', [ 'action' => 'edit', 'id' => $this->id ]));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo '<div class="form-group">';
    echo $this->formHidden($form->get('id'));
    echo $this->formRow($form->get('locale'));
    echo '</div><div class="form-group">';
    echo $this->formSubmit($form->get('submit'));
    echo '</div';
    echo $this->form()->closeTag();
?>
