<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Application\ResultSet\Locale   $locales
 * @var \Application\Model\Locale       $locale
 */

$title = $this->translate('Locale configuration');
$this->headTitle($title);
?>

<div class="card mt-4">
    <div class="card-header">
        <?= $this->escapeHtml($title); ?>
    </div>
    <div class="card-body">
        <p class="form-group">
            <a class="btn btn-info" href="<?= $this->url('locale', [ 'action'=>'add' ]);?>"><?= $this->translate('Add new locale') ?></a>
        </p>
        <table class="table">
            <tr>
                <th><?= $this->translate('Locale') ?></th>
                <th>&nbsp;</th>
            </tr>
            <?php foreach ($locales as $locale): ?>
                <tr>
                    <td>
                        <img src="<?= $this->basePath('img/flags/' . strtolower(substr($locale->getLocale(), 3, 2))) ?>.png" alt="" />
                        <?= $this->escapeHtml($this->translate($locale->getLocale())); ?>
                    </td>
                    <td class="text-right">
                        <a class="btn btn-info btn-sm" href="<?= $this->url('locale', [ 'action'=>'edit', 'id' => $locale->getId() ]);?>"><?= $this->translate('Edit') ?></a>
                        <a class="btn btn-danger btn-sm" href="<?= $this->url('locale', [ 'action'=>'delete', 'id' => $locale->getId() ]);?>"><?= $this->translate('Delete') ?></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>
