<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Zend\Db\ResultSet\ResultSet    $locales
 * @var \Application\Model\Locale       $locale
 */

$title = $this->translate('Locale configuration');
$this->headTitle($title);
?>

<div class="card">
    <div class="card-header">
        <?= $this->escapeHtml($title); ?>
    </div>
    <div class="card-body">
        <p class="form-group pull-right">
            <a class="btn btn-info" href="<?= $this->url('locale', [ 'action'=>'add' ]);?>">
                <i class="fa fa-plus"></i><span class="ml-2"><?= $this->translate('Add new locale') ?></span>
            </a>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col"><?= $this->translate('Configured locales') ?></th>
                    <th scope="col">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($locales as $locale): ?>
                    <tr>
                        <td scope="row">
                            <?= $this->flag($locale); ?>
                            <?= $this->escapeHtml($this->translate($locale->getLocale())); ?>
                        </td>
                        <td class="text-right">
                            <a class="btn btn-info btn-sm" href="<?= $this->url('locale', [ 'action'=>'edit', 'id' => $locale->getId() ]);?>">
                                <i class="fa fa-edit"></i><span class="ml-2"><?= $this->translate('Edit') ?></span>
                            </a>
                            <a class="btn btn-danger btn-sm" href="<?= $this->url('locale', [ 'action'=>'delete', 'id' => $locale->getId() ]);?>">
                                <i class="fa fa-trash"></i><span class="ml-2"><?= $this->translate('Delete') ?></span>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
