<?= $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <?= $this->headTitle($this->translate('Magento translation tool'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?= $this->headLink([ 'rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico' ])
             ->prependStylesheet($this->basePath() . '/css/style.css')
             ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
             ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
         ?>

        <!-- Scripts -->
        <?php $this->inlineScript()
            ->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js')
            ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js')
            ->prependFile('https://code.jquery.com/jquery-3.2.1.slim.min.js')
        ?>

        <?php /*
        <script>
            $(document).delegate('*[data-toggle="lightbox"]', 'click', function (event) {
                event.preventDefault();
                $(this).ekkoLightbox();
            });
        </script>
        */ ?>

        <script type="text/javascript">
            document.documentElement.className = 'no-fouc';
        </script>
    </head>
    <body>
        <nav id="navbar" class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" role="navigation">
            <div class="container">
                <a class="navbar-brand" href="#"><?= $this->translate('Magento translation tool') ?></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarContent">
                    <?= $this->navigation('navigation')->menu()->setPartial('navigation.phtml')->render() ?>
                </div>
            </div>
        </nav>
        <main role="main" class="container">
            <?= $this->content; ?>
            <hr />
            <footer>
                <p>&copy; <?= date('Y') ?> by Netresearch</p>
            </footer>
        </main>
        <?= $this->inlineScript() ?>
        <script type="text/javascript">

            $("document").ready(function () {
                $('.no-fouc').removeClass('no-fouc');
            });

        </script>
    </body>
</html>
