<?php
/**
 * @var $this Zend\View\Renderer\PhpRenderer
 *
 * @var array $downloadFiles - [path|locale|filename] strings
 */
?>

<div class="card mt-4">
    <div class="card-header">Export CSV</div>
    <div class="card-body">
        <form action="<?php echo $this->url('admin', [ 'action' => 'export' ]) ?>" method="post" role="form">
            <div class="form-group">
                <label for="translationFile">Translation file</label>
                <select class="form-control" id="translationFile" name="translation_file[]" multiple="multiple">
                    <?php foreach ($translationFiles as $translationFile): ?>
                        <option value="<?php echo $translationFile->getFilename(); ?>"><?php echo $translationFile->getFilename(); //TODO escape ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <label for="language">Language</label>
                <select class="form-control" id="language" name="locale[]" multiple="multiple">
                    <?php foreach ($supportedLocales as $locale): ?>
                        <option value="<?php echo $locale->getLocale() ?>"><?php echo $locale->getLocale() ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <label for="exportCsv">export to</label>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="export_type" id="exportCsv" value="csv" disabled="disabled" checked="checked" /> CSV (Download)
                    </label>
                    <br/>
                    <label>
                        <input type="checkbox" name="export_type" value="git" /> Git (Commit)
                    </label>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Start Export</button>
        </form>
    </div>
</div>

<?php if (count($downloadFiles)): ?>
    <p>Please download the following files:</p>
<?php else: ?>
    <p>No files exported.</p>
<?php endif; ?>

<ul>
    <?php foreach ($downloadFiles as $file): ?>
    <li><a href="<?php echo $this->serverUrl($file['path']) ?>"><?php echo $file['locale']?> - <?php echo $file['filename'] ?></a></li>
    <?php endforeach; ?>
</ul>

<p><a href="<?php echo $this->url('admin') ?>">
    <span class="glyphicon glyphicon-chevron-left"></span>
    Back to admin
</a></p>