<?php
/**
 * @var Zend\View\Renderer\PhpRenderer         $this
 * @var \Application\ResultSet\SupportedLocale $supportedLocales
 * @var \Application\ResultSet\Translation     $translations
 * @var \Application\ResultSet\TranslationBase $translationBase
 * @var \Application\ResultSet\TranslationFile $translationFiles
 */
?>
<h2><?= $this->translate('Import') ?></h2>
<div class="card mt-4">
    <div class="card-header">Import default CSV (Dummy, not yet implemented!)</div>
    <div class="card-body">

        <form action="<?php echo $this->url('admin', [ 'action' => 'import' ]) ?>" method="post" multipart="" enctype="multipart/form-data" role="form">
            <div class="form-group">
                <label class="control-label" for="filebutton">Select File(s)</label>
                <input type="file" name="img[]" id="files" class="input-large" multiple>
            </div>
            <div class="form-group row">
                <div class="col-sm-2">
                    <label for="language">Import as language</label>
                    <input type="text" class="form-control"  maxlength="5" size="5" name="language" value="en_US" placeholder="en_US">
                </div>
            </div>
            <div class="form-group">
                <button type="submit" id="submit" name="Import" class="btn btn-primary button-loading" data-loading-text="Loading...">Start Import</button>
            </div>
        </form>
    </div>
</div>
