<?php
/**
 * @var Zend\View\Renderer\PhpRenderer         $this
 * @var \Application\ResultSet\SupportedLocale $supportedLocales
 * @var \Application\ResultSet\Translation     $translations
 * @var \Application\ResultSet\TranslationBase $translationBase
 * @var \Application\ResultSet\TranslationFile $translationFiles
 */
?>
<h2>Admin dashboard</h2>
<div class="panel panel-default">
    <div class="panel-heading">Import default CSV (Dummy, not yet implemented!)</div>
    <div class="panel-body">
        <form action="<?php echo $this->url('admin', [ 'action' => 'import' ]) ?>" method="post" multipart="" enctype="multipart/form-data" role="form">
            <div class="form-group">
                <label class="control-label" for="filebutton">Select File(s)</label>
                <input type="file" name="img[]" id="files" class="input-large" multiple>
            </div>
            <div class="form-group row">
                <div class="col-sm-2">
                    <label for="language">Import as language</label>
                    <input type="text" class="form-control"  maxlength="5" size="5" name="language" value="en_US" placeholder="en_US">
                </div>
            </div>
            <div class="form-group">
                <button type="submit" id="submit" name="Import" class="btn btn-primary button-loading" data-loading-text="Loading...">Start Import</button>
            </div>
        </form>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">Export CSV</div>
    <div class="panel-body">
        <form action="<?php echo $this->url('admin', [ 'action' => 'export' ]) ?>" method="post" role="form">
            <div class="form-group">
                <label for="translationFile">Translation file</label>
                <select class="form-control" id="translationFile" name="translation_file[]" multiple="multiple">
                    <?php foreach ($translationFiles as $translationFile): ?>
                        <option value="<?php echo $translationFile->getFilename(); ?>"><?php echo $translationFile->getFilename(); //TODO escape ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <label for="language">Language</label>
                <select class="form-control" id="language" name="locale[]" multiple="multiple">
                    <?php foreach ($supportedLocales as $locale): ?>
                        <option value="<?php echo $locale->getLocale() ?>"><?php echo $locale->getLocale() ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="form-group">
                <label for="exportCsv">export to</label>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="export_type" id="exportCsv" value="csv" disabled="disabled" checked="checked" /> CSV (Download)<br/>
                        <input type="checkbox" name="export_type" value="git" /> Git (Commit)<br/>
                    </label>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Start Export</button>
        </form>
    </div>
</div>