<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer    $this
 * @var \Zend\Db\ResultSet\ResultSet       $suggestions
 * @var \Zend\Db\ResultSet\ResultSet       $supportedLocales
 * @var \Application\ResultSet\Translation $translations
 * @var \Application\Model\TranslationBase $baseTranslation
 * @var \Application\Model\Translation     $translation
 * @var \Application\Model\Locale          $locale
 * @var string $currentLocale
 * @var string $currentTranslationFile
 * @var array $messages of strings
 * @var int $previousItemId
 * @var int $nextItemId
 */
?>

<?php /*
<div class="row">
    <div class="col-12">
        <div class="card mt-4">
            <div class="card-header">
                <strong><?= $this->translate('Filter') ?></strong>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-12">
                        <b><?= $this->translate('Selected file:') ?></b> <span class="label label-primary"><?= $this->escapeHtml($currentTranslationFile) ?></span>
                    </div>
                    <div class="col-12 mt-4">
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <label class="input-group-text" for="inputGroupLocaleSelect"><?= $this->translate('Language') ?></label>
                            </div>
                            <select class="custom-select" id="inputGroupLocaleSelect">
                                <?php foreach ($supportedLocales as $locale): ?>
                                    <option value="<?= $locale->getLocale() ?>"<?php if ($currentLocale === $locale->getLocale()): ?> selected="selected"<?php endif; ?>><?= $this->translate($locale->getLocale()) ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
*/ ?>

<form action="" method="post">
    <div class="row">
        <div class="col-12">
            <?php $rowName         = 'row' . $currentLocale; ?>
            <?php $unclearSelected = $translations[$currentLocale]->getUnclear(); ?>

            <input type="hidden" name="baseId" value="<?= $baseTranslation->getId() ?>">
            <input type="hidden" name="locale" value="<?= $this->escapeHtmlAttr($currentLocale) ?>">
            <input type="hidden" name="id" value="<?= $translations[$currentLocale]->getId() ?>">

            <div class="card mt-4 border-info">
                <div class="card-header text-white bg-info">
                    <strong>
                        <?= $this->translate('Translation') ?>
                        <span class="pull-right">
                            &nbsp;
                            <img src="<?= $this->basePath('img/flags/' . strtolower(substr($currentLocale, 3, 2))) ?>.png" title="<?= $this->translate($currentLocale) ?>" alt="">
                        </span>
                        <?php if (empty($translations[$currentLocale]->getTranslation())): ?>
                            <span class="pull-right fa fa-ban text-danger" style="margin-top: 6px;" title="<?= $this->translate('Missing translation') ?>">&nbsp;</span>
                        <?php else: ?>
                            <?php if ($unclearSelected): ?>
                                <span class="pull-right fa fa-exclamation-triangle" style="margin-top: 6px;" title="<?= $this->translate('Unclear translation') ?>">&nbsp;</span>
                            <?php endif; ?>
                        <?php endif; ?>
                    </strong>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label><?= $this->translate('Origin source') ?></label>
                        <input type="text" class="form-control" readonly value="<?= $this->escapeHtml($baseTranslation->getOriginSource()); ?>">
                    </div>

                    <div class="form-group">
                        <label for="translationInput"><?= $this->translate('Current translation') ?></label>
                        <input id="translationInput" type="text" class="form-control" autofocus name="translation" value="<?= $this->escapeHtml($translations[$currentLocale]->getTranslation()); ?>">
                    </div>

                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" name="unclear" id="unclearInput" value="1"<?php if ($unclearSelected): ?> checked="checked"<?php endif; ?>>
                        <label class="form-check-label" for="unclearInput"><?= $this->translate('Translation is unclear') ?></label>
                        <small class="form-text text-muted">
                            <?= $this->translate('String is usually marked as unclear if translation should be reviewed by another person.') ?>
                        </small>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 mt-4">
            <button type="submit" value="all" name="rowid" class="btn btn-success pull-right" id="save-all-button"><?= $this->translate('Save') ?></button>
        </div>
    </div>

<?php /*
    <div class="row">
        <div class="col-md-12">
            <div class="card mt-4">
                <div class="card-header">
                    <strong>Existing suggestions</strong>
                    <span class="badge badge-info pull-right"><?= $currentLocale ?></span>
                    <span class="pull-right">&nbsp;<img src="<?= $this->basePath('img/flags/' . strtolower(substr($currentLocale, 0, 2))) ?>.png" alt="<?= $currentLocale ?>" />&nbsp;</span>
                </div>
                <div class="card-body suggestionlist">
                    <?php foreach ($suggestions as $suggestion): ?>
                        <span class="badge badge-info" id="suggestion_<?= $suggestion->getSuggestionId() ?>">
                            <?= $suggestion->getSuggestedTranslation() ?>
                        </span>
                    <?php endforeach; ?>

                    <?php //echo $this->escapeHtml($translations[$currentLocale]->getTranslation()); ?>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card mt-4">
                <div class="card-header">
                    <strong>Submit a new suggestion</strong>
                    <span class="badge badge-info pull-right"><?= $currentLocale ?></span>
                    <span class="pull-right">&nbsp;<img src="<?= $this->basePath('img/flags/' . strtolower(substr($currentLocale, 0, 2))) ?>.png" alt="<?= $currentLocale ?>" />&nbsp;</span>
                </div>
                <div class="card-body">
                    <div class="input-group col-md-12">
                        <textarea class="form-control" rows="3" name="<?= $rowName ?>_suggestedTranslation"></textarea>
                    </div>
                    <button type="submit" value="<?= $rowName ?>" name="rowid" class="btn btn-primary">Submit suggestion</button>
                </div>
            </div>
        </div>
    </div>
*/ ?>
    <div class="row">
        <div class="col-md-12 mt-4">
            <a class="btn btn-dark pull-left" href="<?= $this->url('index', [ 'action' => 'edit', 'base_id' => $previousItemId ], [ 'query' => [ 'locale' => $currentLocale ] ]) ?>">
                <i class="fa fa-angle-left"></i>&nbsp;<?= $this->translate('Previous translation') ?>
            </a>
            <a class="btn btn-dark pull-right" href="<?= $this->url('index', [ 'action' => 'edit', 'base_id' => $nextItemId ], [ 'query' => [ 'locale' => $currentLocale ] ]) ?>">
                <?= $this->translate('Next translation') ?>&nbsp;<i class="fa fa-angle-right"></i>
            </a>
        </div>
    </div>

<?php /*
    <div class="row">
        <div class="col-md-12">
            <div class="card mt-4" role="tablist" aria-multiselectable="true" data-toggle="collapse" data-target="#MageVersions">
                <div class="card-header">
                    <strong>Further translations (MageVersions)</strong>
                </div>
                <div class="card-body collapse" id="MageVersions">
                    <table class="table table-hover table-striped" id="translation-grid">
                        <tr>
                            <th>MageVersion<th>
                            <th>Current translation<th>
                            <th colspan="2" class="text-center"><span title="Unclear translation">Status</span></th>
                            <th>t.b.d.<th>
                            <th><th>
                        </tr>
                        <?php foreach ($translations as $locale => $translation): ?>
                            <?php if ($locale == $currentLocale) continue; ?>
                            <?php ?>
                            <?php $rowName = 'row' . $locale; ?>
                            <tr id="<?= $rowName ?>">
                                <td><?= $this->escapeHtml($locale) ?><td>
                                <td><?= $this->escapeHtml($translation->getTranslation()) ?><td>
                                <td>
                                    <?php if ($translation->getUnclear()): ?>
                                        <i class="fa fa-exclamation-triangle unclear" title="Unclear translation"></i>
                                    <?php endif; ?>
                                </td>
                                <td>
                                    <input type="radio" name="<?= $rowName?>_unclearTranslation" value="1" <?= ($translation->getUnclear()) ? 'checked="checked"':'' ?>>
                                    <!-- <input type="checkbox" name="<?= $rowName?>_unclearTranslation" value="1" <?= ($translation->getUnclear()) ? 'checked="checked"':'' ?>> -->
                                </td>
                                <td class="suggested-translation">
                                    <input type="text" class="form-control" name="<?= $rowName?>_suggestedTranslation" value="" />
                                <td>
                                <td>
                                    <div style="min-width: 125px">
                                        <input type="hidden" name="<?= $rowName ?>_locale" value="<?= $locale ?>" />
                                        <input type="hidden" name="<?= $rowName?>_id" value="<?= $this->escapeHtmlAttr($translation->getId())?>" />
                                        <button type="submit" value="<?= $rowName?>" name="rowid" class="btn btn-primary" data-toggle="tooltip" data-placement="right" title="Submit Suggestion"><span class="fa fa-plus"></span></button>
                                        &nbsp;
                                        <a class="btn btn-info" data-toggle="tooltip" data-placement="right" title="See Details" href="<?= $this->url('index', [ 'action' => 'edit', 'base_id' => $baseTranslation->getId() ], [ 'query' => [ 'locale' => $locale ] ]) ?>"><span class="fa fa-search"></span></a>
                                    </div>
                                <td>
                            </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </div>
    </div>
*/ ?>

    <div class="row">
        <div class="col-md-12">
                <div class="card mt-4" role="tablist" aria-multiselectable="true" data-target="#locales">
                <div class="card-header">
                    <strong>Further translations (locales)</strong>
                </div>
                <div class="card-body" id="locales">
                    <table class="table table-hover" id="translation-grid">
                        <tr>
                            <th>Locale<th>
                            <th>Current translation<th>
                            <th>Status</th>
<?php /*
                            <th>Add Suggestion<th>
*/ ?>
                            <th width="10%"><th>
                        </tr>
                        <?php foreach ($translations as $locale => $translation): ?>
                            <?php if ($locale === $currentLocale) continue; ?>

                            <?php $detailUrl = $this->url('index', [ 'action' => 'edit', 'base_id' => $baseTranslation->getId() ], [ 'query' => [ 'locale' => $locale ] ]); ?>
                            <?php $rowName   = 'row' . $locale; ?>
                            <tr id="<?= $rowName ?>">
                                <td>
                                    <img src="<?= $this->basePath('img/flags/' . strtolower(substr($locale, 3, 2))) ?>.png" title="<?= $this->translate($locale) ?>" alt="">
                                    <?= $this->escapeHtml($locale) ?>
                                <td>
                                <td>
                                    <a href="<?= $detailUrl ?>">
                                        <?= $this->escapeHtml($translation->getTranslation()) ?>
                                    </a>
                                <td>
                                <td>
                                    <?php if (empty($translation->getTranslation())): ?>
                                        <i class="fa fa-ban text-danger" title="<?= $this->translate('Missing translation') ?>"></i>
                                    <?php else: ?>
                                        <?php if ($translation->getUnclear()): ?>
                                            <i class="fa fa-exclamation-triangle text-warning" title="<?= $this->translate('Unclear translation') ?>"></i>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </td>
<?php /*
                                <td>
                                    <input type="radio" name="<?= $rowName?>_unclearTranslation" value="1" <?= ($translation->getUnclear()) ? 'checked="checked"':'' ?>>
                                </td>
                                <td class="suggested-translation">
                                    <input type="text" class="form-control" name="<?= $rowName?>_suggestedTranslation" value="" />
                                <td>
*/ ?>
                                <td class="text-right">
<?php /*
                                    <input type="hidden" name="<?= $rowName ?>_locale" value="<?= $locale ?>" />
                                    <input type="hidden" name="<?= $rowName?>_id" value="<?= $this->escapeHtmlAttr($translation->getId())?>" />
                                    <button type="submit" value="<?= $rowName?>" name="rowid" class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="right" title="Submit Suggestion"><span class="fa fa-plus"></span></button>
*/ ?>
                                    <a class="btn btn-info btn-sm" data-toggle="tooltip" data-placement="right" title="See Details" href="<?= $detailUrl ?>"><span class="fa fa-search"></span></a>
                                <td>
                            </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </div>
    </div>
</form>

<?php $this->inlineScript()->captureStart(); ?>

$("document").ready(function () {
    $('#inputGroupLocaleSelect').change(function () {
        var url = "<?= $this->url('index', [ 'action' => 'edit', 'base_id' => $baseTranslation->getId() ]); ?>?";

        url += "locale=" + $('#inputGroupLocaleSelect').val() + "&";

        window.location.href = url;
    });
});

<?php $this->inlineScript()->captureEnd(); ?>
