<?php
/**
 * @var Zend\View\Renderer\PhpRenderer $this
 *
 * @var \Application\ResultSet\Locale $supportedLocales
 * @var string $currentLocale
 * @var string $currentTranslationFile
 * @var array $messages of strings
 * @var \Application\Model\TranslationBase $baseTranslation
 * @var \Application\ResultSet\Translation $translations with index locale
 * @var \Application\ResultSet\Suggestion $suggestions with index suggestion_id
 * @var int $previousItemId
 * @var int $nextItemId
 */
?>
<ul class="messages row">
    <?php if (isset($messages)): ?>
        <?php foreach ($messages as $messageLevel => $messageLevelContainer): ?>
            <?php foreach ($messageLevelContainer as $message): ?>
                <li class="alert alert-<?= $this->escapeHtmlAttr($messageLevel); ?>" role="alert">
                    <?= $this->escapeHtml($message); ?>
                </li>
            <?php endforeach; ?>
        <?php endforeach; ?>
    <?php endif; ?>
</ul>

<div class="card">
    <div class="card-header"><b>Basic data</b></div>
    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <div class="btn-group">
                    <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown">
                        Language <span class="caret"></span>
                    </button>
                    <div class="dropdown-menu">
                        <?php foreach ($supportedLocales as $locale): ?>
                            <a class="dropdown-item" href="<?= $this->url('index', [ 'action' => 'edit', 'base_id' => $baseTranslation->getBaseId() ], [ 'query' => [ 'locale' => $locale->getLocale() ] ]); ?>">
                                <?= $locale->getLocale() ?></a>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
            <div class="col-12">
                <b>selected file:</b> <span class="label label-primary"><?= $this->escapeHtml($currentTranslationFile) ?></span>
                <b>selected language:</b> <span class="badge badge-info"><?= $this->escapeHtml($currentLocale) ?></span>
            </div>
        </div>
    </div>
</div>

<form action="" method="post">
    <div class="row">
        <div class="col-md-12">
            <div style="margin-bottom: 25px; overflow: hidden;">
                <a class="btn btn-info pull-left" href="<?= $this->url('index', [ 'action' => 'edit', 'base_id' => $previousItemId ], [ 'query' => [ 'locale' => $currentLocale ] ]) ?>">Previous translation</a>
                <a class="btn btn-info pull-right" href="<?= $this->url('index', [ 'action' => 'edit', 'base_id' => $nextItemId ], [ 'query' => [ 'locale' => $currentLocale ] ]) ?>">Next translation</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <?php $rowName = 'row' .$currentLocale; ?>
            <input type="hidden" name="base_id" value="<?= $baseTranslation->getBaseId() ?>" />
            <input type="hidden" name="<?= $rowName ?>_locale" value="<?= $this->escapeHtmlAttr($currentLocale) ?>" />
            <input type="hidden" name="<?= $rowName ?>_id" value="<?= $translations[$currentLocale]->getTranslationId() ?>" />
            <div class="card">
                <div class="card-header">
                    <strong>Origin source</strong>
                    <?php if ($baseTranslation->getNotInUse()): ?><span class="label label-danger pull-right">Not in use anymore</span>
                    <?php endif; ?>
                </div>
                <div class="card-body">
                    <?= $this->escapeHtml($baseTranslation->getOriginSource()); ?>
                </div>
                <div class="panel-footer">
                    <?php if ('' !== $baseTranslation->getScreenPath()): ?>
                        <a href="<?= $this->basePath('usages/' . $baseTranslation->getScreenPath()) ?>" class="btn btn-info" role="button" data-target="#lightbox" data-toggle="lightbox">
                            <span class="glyphicon glyphicon-camera"></span> Show Context
                        </a>
                    <?php else: ?>
                    <a href="<?= $this->basePath('img/fallback-no-screenshot.png') ?>" class="btn btn-info" role="button" data-target="#lightbox" data-toggle="lightbox" data-width="400">
                        <span class="glyphicon glyphicon-camera"></span> Show Context
                    </a>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <?php $unclearSelected = $translations[$currentLocale]->getUnclearTranslation() ?>
                <div class="card-header">
                    <strong>Current translation</strong>
                    <span class="badge badge-info pull-right"><?= $currentLocale ?></span>
                    <span class="pull-right">&nbsp;<img src="<?= $this->basePath('img/flags/' . strtolower(substr($currentLocale, 0, 2))) ?>.png" alt="<?= $currentLocale ?>" />&nbsp;</span>
                    <?php if ($unclearSelected): ?>
                        <i class="glyphicon glyphicon-exclamation-sign unclear " title="unclear translation"></i>
                    <?php endif; ?>
                </div>
                <div class="card-body">
                    <?= $this->escapeHtml($translations[$currentLocale]->getCurrentTranslation()); ?>
                </div>
                <div class="panel-footer">
                    <input type="checkbox" name="<?= $rowName ?>_unclearTranslation" id="<?= $rowName ?>_unclearTranslation" value="1" <?php if ($unclearSelected) echo 'checked="checked"' ?>/>
                    <label style="font-weight: normal" for="<?= $rowName ?>_unclearTranslation">translation is unclear</label>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <strong>Existing suggestions</strong>
                    <span class="badge badge-info pull-right"><?= $currentLocale ?></span>
                    <span class="pull-right">&nbsp;<img src="<?= $this->basePath('img/flags/' . strtolower(substr($currentLocale, 0, 2))) ?>.png" alt="<?= $currentLocale ?>" />&nbsp;</span>
                </div>
                <div class="card-body suggestionlist">
                    <?php foreach ($suggestions as $suggestion): ?>
                        <span class="badge badge-info" id="suggestion_<?= $suggestion->getSuggestionId() ?>">
                            <?= $suggestion->getSuggestedTranslation() ?>
                        </span>
                    <?php endforeach; ?>

                    <?php //echo $this->escapeHtml($translations[$currentLocale]->getCurrentTranslation()); ?>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <strong>Submit a new suggestion</strong>
                    <span class="badge badge-info pull-right"><?= $currentLocale ?></span>
                    <span class="pull-right">&nbsp;<img src="<?= $this->basePath('img/flags/' . strtolower(substr($currentLocale, 0, 2))) ?>.png" alt="<?= $currentLocale ?>" />&nbsp;</span>
                </div>
                <div class="card-body">
                    <div class="input-group col-md-12">
                        <textarea class="form-control" rows="3" name="<?= $rowName ?>_suggestedTranslation"></textarea>
                        <button type="submit" value="<?= $rowName ?>" name="rowid" class="btn btn-primary btn-lg pull-right" style="margin-top: 15px;">Submit suggestion</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div style="margin-bottom: 25px; overflow: hidden;">
                <a class="btn btn-info pull-left" href="<?= $this->url('index', [ 'action' => 'edit', 'base_id' => $previousItemId ], [ 'query' => [ 'locale' => $currentLocale ] ]) ?>">Previous translation</a>
                <a class="btn btn-info pull-right" href="<?= $this->url('index', [ 'action' => 'edit', 'base_id' => $nextItemId ], [ 'query' => [ 'locale' => $currentLocale ] ]) ?>">Next translation</a>
            </div>
        </div>
    </div>

    <hr/>

    <div class="row">
        <div class="col-md-12">
            <div class="card" id="accordion" role="tablist" aria-multiselectable="true" data-toggle="collapse" data-target="#MageVersions">
                <div class="card-header">
                    <strong>Further translations (MageVersions)</strong>
                </div>
                <div class="card-body collapse" id="MageVersions">
                    <table class="table table-hover table-striped" id="translation-grid">
                        <tr>
                            <th>MageVersion<th>
                            <th>Current translation<th>
                            <th colspan="2" class="text-center"><span title="unclear translation">Status</span></th>
                            <th>t.b.d.<th>
                            <th><th>
                        </tr>
                        <?php foreach ($translations as $locale => $translation): ?>
                            <?php if ($locale == $currentLocale) continue; ?>
                            <?php /* @var $translation \Application\Model\Translation */ ?>
                            <?php $rowName = 'row' . $locale; ?>
                            <tr id="<?= $rowName ?>">
                                <td><?= $this->escapeHtml($locale) ?><td>
                                <td><?= $this->escapeHtml($translation->getCurrentTranslation()) ?><td>
                                <td>
                                    <?php if ($translation->getUnclearTranslation()): ?>
                                        <i class="glyphicon glyphicon-exclamation-sign unclear" title="unclear translation"></i>
                                    <?php endif; ?>
                                </td>
                                <td>
                                    <input type="radio" name="<?= $rowName?>_unclearTranslation" value="1" <?= ($translation->getUnclearTranslation()) ? 'checked="checked"':'' ?>>
                                    <!-- <input type="checkbox" name="<?= $rowName?>_unclearTranslation" value="1" <?= ($translation->getUnclearTranslation()) ? 'checked="checked"':'' ?>> -->
                                </td>
                                <td class="suggested-translation">
                                    <input type="text" class="form-control" name="<?= $rowName?>_suggestedTranslation" value="" />
                                <td>
                                <td>
                                    <div style="min-width: 125px">
                                        <input type="hidden" name="<?= $rowName ?>_locale" value="<?= $locale ?>" />
                                        <input type="hidden" name="<?= $rowName?>_id" value="<?= $this->escapeHtmlAttr($translation->getTranslationId())?>" />
                                        <button type="submit" value="<?= $rowName?>" name="rowid" class="btn btn-primary btn-lg" data-toggle="tooltip" data-placement="right" title="Submit Suggestion"><span class="glyphicon glyphicon-plus"></span></button>
                                        &nbsp;
                                        <a class="btn btn-info btn-lg" data-toggle="tooltip" data-placement="right" title="See Details" href="<?= $this->url('index', [ 'action' => 'edit', 'base_id' => $baseTranslation->getBaseId() ], [ 'query' => [ 'locale' => $locale ] ]) ?>"><span class="glyphicon glyphicon-search"></span></a>
                                    </div>
                                <td>
                            </tr>
                        <?php endforeach; ?>

                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
                <div class="card" id="accordion" role="tablist" aria-multiselectable="true" data-toggle="collapse" data-target="#locales">
                <div class="card-header">
                    <strong>Further translations (locales)</strong>
                </div>
                <div class="card-body collapse" id="locales">
                    <table class="table table-hover table-striped" id="translation-grid">
                        <tr>
                            <th>Locale<th>
                            <th>Current translation<th>
                            <th colspan="2" class="text-center"><span title="unclear translation">Status</span></th>
                            <th>Add Suggestion<th>
                            <th><th>
                        </tr>
                        <?php foreach ($translations as $locale => $translation): ?>
                            <?php if ($locale === $currentLocale) continue; ?>
                            <?php /* @var $translation \Application\Model\Translation */ ?>
                            <?php $rowName = 'row' . $locale; ?>
                            <tr id="<?= $rowName ?>">
                                <td><?= $this->escapeHtml($locale) ?><td>
                                <td><?= $this->escapeHtml($translation->getCurrentTranslation()) ?><td>
                                <td>
                                    <?php if ($translation->getUnclearTranslation()): ?>
                                        <i class="glyphicon glyphicon-exclamation-sign unclear" title="unclear translation"></i>
                                    <?php endif; ?>
                                </td>
                                <td>
                                    <input type="radio" name="<?= $rowName?>_unclearTranslation" value="1" <?= ($translation->getUnclearTranslation()) ? 'checked="checked"':'' ?>>
                                    <!-- <input type="checkbox" name="<?= $rowName?>_unclearTranslation" value="1" <?= ($translation->getUnclearTranslation()) ? 'checked="checked"':'' ?>> -->
                                </td>
                                <td class="suggested-translation">
                                    <input type="text" class="form-control" name="<?= $rowName?>_suggestedTranslation" value="" />
                                <td>
                                <td>
                                    <div style="min-width: 125px">
                                        <input type="hidden" name="<?= $rowName ?>_locale" value="<?= $locale ?>" />
                                        <input type="hidden" name="<?= $rowName?>_id" value="<?= $this->escapeHtmlAttr($translation->getTranslationId())?>" />
                                        <button type="submit" value="<?= $rowName?>" name="rowid" class="btn btn-primary btn-lg" data-toggle="tooltip" data-placement="right" title="Submit Suggestion"><span class="glyphicon glyphicon-plus"></span></button>
                                        &nbsp;
                                        <a class="btn btn-info btn-lg" data-toggle="tooltip" data-placement="right" title="See Details" href="<?= $this->url('index', [ 'action' => 'edit', 'base_id' => $baseTranslation->getBaseId() ], [ 'query' => [ 'locale' => $locale ] ]) ?>"><span class="glyphicon glyphicon-search"></span></a>
                                    </div>
                                <td>
                            </tr>
                        <?php endforeach; ?>

                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div style="margin-bottom: 25px; overflow: hidden;">
                <button class="btn btn-info pull-left" href="<?= $this->url('index', [ 'action' => 'edit', 'base_id' => $previousItemId ], [ 'query' => [ 'locale' => $currentLocale  ] ]) ?>">Previous translation</button>
                <button class="btn btn-info pull-right" href="<?= $this->url('index', [ 'action' => 'edit', 'base_id' => $nextItemId ], [ 'query' => [ 'locale' => $currentLocale ] ]) ?>">Next translation</button>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <button type="submit" value="all" name="rowid" class="btn btn-primary pull-right" id="save-all-button">Submit all</button>
        </div>
    </div>
</form>