<?php
/**
 * @var $this Zend\View\Renderer\PhpRenderer
 *
 * @var \Application\ResultSet\Locale          $supportedLocales
 * @var \Application\ResultSet\Translation     $translations
 * @var \Application\ResultSet\TranslationBase $translationBase
 * @var \Application\ResultSet\TranslationFile $translationFiles
 * @var \Application\Model\Translation         $translation
 * @var int $translationsCount
 * @var string $currentLocale
 * @var string[] $currentFile
 * @var bool $currentFilterUnclear
 * @var int $currentPage
 * @var int $currentEPP - entries per page
 * @var int $maxPages
 * @var string[] messages with index messageLevel
 * @var string $jumpToRow
 */
?>

<?php if (isset($messages) && count($messages)): ?>
    <ul class="messages row">
        <?php foreach ($messages as $messageLevel => $messageLevelContainer): ?>
            <?php foreach ($messageLevelContainer as $message): ?>
                <li class="alert alert-<?= $this->escapeHtmlAttr($messageLevel); ?>" role="alert">
                    <?= $this->escapeHtml($message); ?>
                </li>
            <?php endforeach; ?>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>

<div class="row">
    <div class="col-12">
        <div class="card filter-area mt-4">
            <div class="card-header"><strong><?= $this->translate('Filter') ?></strong></div>
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="btn-group">
                            <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown">
                                <?= $this->translate('Translation file') ?> <span class="caret"></span>
                            </button>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="<?= $this->url('home', [], [ 'query' => [ 'locale' => $currentLocale, 'file' => null, 'filter_unclear_translation' => $currentFilterUnclear ] ]); ?>"><?= $this->translate('all files') ?></a>
                                <?php foreach ($translationFiles as $translationFile): ?>
                                    <a class="dropdown-item" href="<?= $this->url('home', [], [ 'query' => [ 'locale' => $currentLocale, 'file' => $translationFile->getFilename(), 'filter_unclear_translation' => $currentFilterUnclear ] ]); ?>">
                                        <?= $translationFile->getFilename() ?></a>
                                <?php endforeach; ?>
                            </div>
                        </div>
                        <div class="btn-group">
                            <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown">
                                <?= $this->translate('Language') ?> <span class="caret"></span>
                            </button>
                            <div class="dropdown-menu">
                                <?php foreach ($supportedLocales as $locale): ?>
                                    <a class="dropdown-item" href="<?= $this->url('home', [], [ 'query' => [ 'locale' => $locale->getLocale(), 'file' => $currentFile, 'filter_unclear_translation' => $currentFilterUnclear ] ]); ?>">
                                        <?= $locale->getLocale() ?></a>
                                <?php endforeach; ?>
                            </div>
                        </div>
                        <div id="entries-per-page-button" class="btn-group">
                            <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown">
                                <?= $this->translate('Entries per page') ?> <span class="caret"></span>
                            </button>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="<?= $this->url('home', [], [ 'query' => [ 'locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => $currentFilterUnclear, 'page' => $currentPage, 'epp' => 25 ] ]); ?>">
                                    25
                                </a>
                                <a class="dropdown-item" href="<?= $this->url('home', [], [ 'query' => [ 'locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => $currentFilterUnclear, 'page' => $currentPage, 'epp' => 50 ] ]); ?>">
                                    50
                                </a>
                                <a class="dropdown-item" href="<?= $this->url('home', [], [ 'query' => [ 'locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => $currentFilterUnclear, 'page' => $currentPage, 'epp' => 100 ] ]); ?>">
                                    100
                                </a>
                                <a class="dropdown-item" href="<?= $this->url('home', [], [ 'query' => [ 'locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => $currentFilterUnclear, 'page' => $currentPage, 'epp' => 250 ] ]); ?>">
                                    250
                                </a>
                                <a class="dropdown-item" href="<?= $this->url('home', [], [ 'query' => [ 'locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => $currentFilterUnclear, 'page' => $currentPage, 'epp' => 'all' ] ]); ?>">
                                    <?= $this->translate('all' ) ?>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 text-right">
                        <p>
                            <strong><?= $this->translate('selected file:') ?></strong>
                            <?php if (empty($currentFile)): ?>
                                <span class="label label-info"><?= $this->translate('all files') ?></span>
                            <?php else: ?>
                                <?php foreach ($currentFile as $fileName): ?>
                                    <span class="label label-primary"><?= $fileName ?></span>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </p>
                        <p>
                            <strong><?= $this->translate('selected language:') ?></strong> <span class="badge badge-info"><?= $currentLocale ?></span>
                        </p>
                        <p>
                            <strong><?= $this->translate('per page:') ?> </strong><span class="badge badge-info"><?= (null !== $currentEPP) ? (int)$currentEPP : $this->translate('all') ?></span>
                        </p>
                        <p>
                            <strong><?= $this->translate('unclear translations:') ?> </strong>
                            <?php if ($currentFilterUnclear): ?>
                                <button class="btn btn-info" onclick="location.href='<?= $this->url('home', [], [ 'query' => [ 'locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => 0 ] ]) ?>'">
                                    <?= $this->translate('show only unclear') ?>
                                </button>
                            <?php else: ?>
                                <button class="btn btn-outline-info" onclick="location.href='<?= $this->url('home', [], [ 'query' => [ 'locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => 1 ] ]) ?>'">
                                    <?= $this->translate('show only unclear') ?>
                                </button>
                            <?php endif; ?>
                        </p>
                    </div>
                    <div class="col-12">
                        <ul class="pagination">
                            <?php if ($currentPage > 1): ?>
                                <li><a class="badge badge-pill badge-info" href="<?= $this->url('home', [], [ 'query' => [ 'locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => $currentFilterUnclear, 'page' => $currentPage - 1, 'epp' => $currentEPP ] ]); ?>" aria-label="Previous">
                                        &laquo;
                                    </a></li>
                            <?php endif; ?>
                            <?php for ($i = 1; $i <= $maxPages; $i++): ?>
                                <?php $class = ($i == $currentPage) ? 'active' : ''; ?>
                                <li class="<?= $class ?>"><a class="badge badge-pill badge-info" href="<?= $this->url('home', [], [ 'query' => [ 'locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => $currentFilterUnclear, 'page' => $i, 'epp' => $currentEPP ] ]); ?>">
                                        <?= $i ?>
                                    </a></li>
                            <?php endfor; ?>
                            <?php if ($currentPage < $maxPages): ?>
                                <li><a class="badge badge-pill badge-info" href="<?= $this->url('home', [], [ 'query' => [ 'locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => $currentFilterUnclear, 'page' => $currentPage + 1, 'epp' => $currentEPP ] ]); ?>" aria-label="Next">
                                        &raquo;
                                    </a></li>
                            <?php endif; ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card mt-4">
                    <div class="card-header"><strong><?= $this->translate('overall view list') ?></strong> (<?= count($translations) ?> / <?= (int)$translationsCount ?> <?= $this->translate('elements') ?>)</div>
                    <div class="card-body">
                        <form action="" method="post">
                            <input type="hidden" name="translation_locale" value="<?= $this->escapeHtmlAttr($currentLocale) ?>" />
                            <table class="table table-hover" id="translation-grid">
                                <tr>
                                    <th><?= $this->translate('ID') ?></th>
                                    <th><?= $this->translate('Origin source') ?></th>
                                    <th><?= $this->translate('Current translation') ?></th>
                                    <th><span title="<?= $this->translate('unclear translation') ?>"><?= $this->translate('Status') ?></span></th>
                                    <th><?= $this->translate('New suggested translation') ?></th>
                                    <th></th>
                                </tr>
                                <?php foreach ($translations as $translation): ?>
                                    <?php $base = $translationBase->getById($translation->getBaseId()) ?>
                                    <?php $rowName = 'row' . $translation->getBaseId(); ?>
                                    <tr id="<?= $rowName ?>">
                                        <td><?= $translation->getBaseId() ?></td>
                                        <td>
                                            <?php if ($base): ?>
                                                <?= $this->escapeHtml($base->getOriginSource()) ?>
                                            <?php endif; ?>
                                        </td>
                                        <td><?= $this->escapeHtml($translation->getTranslation()) ?></td>
                                        <td class="text-center">
                                            <?php if ($translation->getUnclear()): ?>
                                                <button class="unclear-translation" title="<?= $this->translate('unclear translation at the moment') ?>" type="button"
                                                        onclick="toggleUnclearTranslation($(this))" data-translation-id="<?= $this->escapeHtmlAttr($translation->getId())?>">
                                                    <i class="fa fa-exclamation-triangle unclear"></i>
                                                </button>
                                            <?php else: ?>
                                                <button class="unclear-translation" title="<?= $this->translate('clear translation at the moment') ?>" type="button"
                                                        onclick="toggleUnclearTranslation($(this))" data-translation-id="<?= $this->escapeHtmlAttr($translation->getId())?>">
                                                    <i class="fa fa-check-circle clear"></i>
                                                </button>
                                            <?php endif; ?>
                                        </td>
                                        <td class="suggested-translation">
                                            <input type="text" class="form-control" name="<?= $rowName?>_suggestedTranslation" value="" />
                                        </td>
                                        <td>
                                            <div style="min-width: 125px">
                                                <input type="hidden" name="<?= $rowName?>_baseId" value="<?= $this->escapeHtmlAttr($translation->getBaseId())?>" />
                                                <input type="hidden" name="<?= $rowName?>_translationId" value="<?= $this->escapeHtmlAttr($translation->getId())?>" />
                                                <button type="submit" value="<?= $rowName?>" name="rowid" class="btn btn-primary btn-lg" data-toggle="tooltip" data-placement="right" title="<?= $this->translate('Add suggestion') ?>"><span class="fa fa-plus"></span></button>
                                                &nbsp;
                                                <a class="btn btn-info btn-lg" data-toggle="tooltip" data-placement="right" title="<?= $this->translate('See Details') ?>" href="<?= $this->url('index', [ 'action' => 'edit', 'base_id' => $translation->getBaseId() ], [ 'query' => [ 'locale' => $currentLocale ] ]) ?>"><span class="fa fa-search"></span></a>
                                            </div>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>

                            </table>
                            <button type="submit" value="all" name="rowid" class="btn btn-info"><?= $this->translate('Submit all') ?></button>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<script>
    <?php if ($jumpToRow): ?>
        $(document).ready(function () {
            // if some suggestion is saved, jump to the row in the grid to be in focus to the next data set
            $('html, body').animate({
                scrollTop: $("#<?= $jumpToRow ?>").offset().top - $("#navbar").outerHeight()
            }, 1000);
        });
    <?php endif; ?>

    // toggle unclear translation flag
    function toggleUnclearTranslation(toggleButton) {
        var translationId = toggleButton.data("translation-id");
        $.ajax({
            type: "POST",
            url: "<?= $this->url('ajax', [ 'action' => 'toggle_unclear' ]); ?>",
            data: {"translation_id": translationId},
            success: function(data) {
                if (false == data.success) {
                    alert("An error occurred toggling the unclear status of element " + translationId + ":\n" + data.error);
                    return;
                }

                // change status in frontend
                if (false == data.new_state) {
                    toggleButton.attr("title", "clear translation at the moment");
                    toggleButton.html("<i class=\"fa fa-check-circle clear\"></i>");
                } else {
                    toggleButton.attr("title", "unclear translation at the moment");
                    toggleButton.html("<i class=\"fa fa-exclamation-triangle unclear\"></i>");
                }
            },
            error: function() {
                alert("An error occurred toggling the unclear translation status");
            }
        });
    }
</script>
