<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer        $this
 *
 * @var \Application\ResultSet\Locale          $supportedLocales
 * @var \Application\ResultSet\Translation     $translations
 * @var \Application\ResultSet\TranslationBase $translationBase
 * @var \Application\ResultSet\TranslationFile $translationFiles
 * @var \Application\Model\Translation         $translation
 * @var int $translationsCount
 * @var string $currentLocale
 * @var string $currentFile
 * @var bool $currentFilterUnclear
 * @var int $currentPage
 * @var int $currentEPP - entries per page
 * @var string[] messages with index messageLevel
 * @var string $jumpToRow
 */
?>

<?php if (isset($messages) && count($messages)): ?>
    <?php foreach ($messages as $messageLevel => $messageLevelContainer): ?>
        <?php foreach ($messageLevelContainer as $message): ?>
        <div class="alert alert-<?= $this->escapeHtmlAttr($messageLevel); ?> alert-dismissible fade show" role="alert">
            <?= $this->escapeHtml($message); ?>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <?php endforeach; ?>
    <?php endforeach; ?>
<?php endif; ?>

<div class="row">
    <div class="col-12">
        <div class="card mt-4">
            <div class="card-header">
                <strong><?= $this->translate('Filter') ?></strong>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <label class="input-group-text" for="inputGroupFileSelect"><?= $this->translate('Translation file') ?></label>
                            </div>
                            <select class="custom-select" id="inputGroupFileSelect">
                                <option value=""><?= $this->translate('all files') ?></option>
                                <?php foreach ($translationFiles as $translationFile): ?>
                                    <option value="<?= $translationFile->getFilename() ?>"<?php if ($currentFile === $translationFile->getFilename()): ?> selected="selected"<?php endif; ?>><?= $translationFile->getFilename() ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <label class="input-group-text" for="inputGroupLocaleSelect"><?= $this->translate('Language') ?></label>
                            </div>
                            <select class="custom-select" id="inputGroupLocaleSelect">
                                <?php foreach ($supportedLocales as $locale): ?>
                                    <option value="<?= $locale->getLocale() ?>"<?php if ($currentLocale === $locale->getLocale()): ?> selected="selected"<?php endif; ?>><?= $this->translate($locale->getLocale()) ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <label class="input-group-text" for="inputGroupPageSelect"><?= $this->translate('Entries per page') ?></label>
                            </div>
                            <select class="custom-select" id="inputGroupPageSelect">
                                <option value="10"<?php if ($currentEPP === 10): ?> selected="selected"<?php endif; ?>>10</option>
                                <option value="25"<?php if ($currentEPP === 25): ?> selected="selected"<?php endif; ?>>25</option>
                                <option value="50"<?php if ($currentEPP === 50): ?> selected="selected"<?php endif; ?>>50</option>
                                <option value="100"<?php if ($currentEPP === 100): ?> selected="selected"<?php endif; ?>>100</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-4 text-right">
                        <p>
                            <strong><?= $this->translate('unclear translations:') ?> </strong>
                            <?php if ($currentFilterUnclear): ?>
                                <button class="btn btn-info" onclick="location.href='<?= $this->url('home', [], [ 'query' => [ 'locale' => $currentLocale, 'file' => $currentFile, 'unclear' => 0 ] ]) ?>'">
                                    <?= $this->translate('show only unclear') ?>
                                </button>
                            <?php else: ?>
                                <button class="btn btn-outline-info" onclick="location.href='<?= $this->url('home', [], [ 'query' => [ 'locale' => $currentLocale, 'file' => $currentFile, 'unclear' => 1 ] ]) ?>'">
                                    <?= $this->translate('show only unclear') ?>
                                </button>
                            <?php endif; ?>
                        </p>
                    </div>
                </div>
            </div>
        </div>

        <div class="card mt-4">
            <div class="card-header"><strong><?= $this->translate('overall view list') ?></strong> (<?= count($translations) ?> / <?= (int)$translationsCount ?> <?= $this->translate('elements') ?>)</div>
            <div class="card-body">
                <form action="" method="post">
                    <input type="hidden" name="translation_locale" value="<?= $this->escapeHtmlAttr($currentLocale) ?>" />
                    <table class="table table-hover" id="translation-grid">
                        <tr>
                            <th><?= $this->translate('ID') ?></th>
                            <th><?= $this->translate('Origin source') ?></th>
                            <th><?= $this->translate('Current translation') ?></th>
                            <th width="10%"></th>
<?php /*
                            <th><?= $this->translate('New suggested translation') ?></th>
                            <th></th>
*/ ?>
                        </tr>
                        <?php foreach ($this->translations as $translation): ?>
                            <?php $base      = $translation->getTranslationBase(); ?>
                            <?php $rowName   = 'row' . $base->getId(); ?>
                            <?php $detailUrl = $this->url('index', [ 'action' => 'edit', 'base_id' => $base->getId() ], [ 'query' => [ 'locale' => $currentLocale ] ]); ?>
                            <tr id="<?= $rowName ?>">
                                <td>
                                    <?= $base->getId() ?>
                                </td>
                                <td>
                                    <?php if ($base): ?>
                                        <a href="<?= $detailUrl ?>">
                                            <?= $this->escapeHtml($base->getOriginSource()) ?>
                                        </a>
                                    <?php endif; ?>
                                </td>
                                <td>
                                    <a href="<?= $detailUrl ?>">
                                        <?= $this->escapeHtml($translation->getTranslation()) ?>
                                    </a>
                                </td>
                                <td class="text-right">
                                    <?php if ($translation->getUnclear()): ?>
                                        <button class="btn btn-warning btn-sm unclear-translation" title="<?= $this->translate('unclear translation at the moment') ?>" type="button"
                                            onclick="toggleUnclearTranslation($(this))" data-translation-id="<?= $this->escapeHtmlAttr($translation->getId())?>">
                                            <i class="fa fa-exclamation-triangle unclear"></i>
                                        </button>
                                    <?php else: ?>
                                        <button class="btn btn-success btn-sm unclear-translation" title="<?= $this->translate('clear translation at the moment') ?>" type="button"
                                            onclick="toggleUnclearTranslation($(this))" data-translation-id="<?= $this->escapeHtmlAttr($translation->getId())?>">
                                            <i class="fa fa-check-circle clear"></i>
                                        </button>
                                    <?php endif; ?>

<?php /*
                                </td>
                                <td class="suggested-translation">
                                    <input type="text" class="form-control" name="<?= $rowName?>_suggestedTranslation" value="" />
                                </td>
                                <td>
*/ ?>
                                    <input type="hidden" name="<?= $rowName?>_baseId" value="<?= $this->escapeHtmlAttr($base->getId())?>" />
                                    <input type="hidden" name="<?= $rowName?>_translationId" value="<?= $this->escapeHtmlAttr($translation->getId())?>" />
<?php /*
                                        <button type="submit" value="<?= $rowName?>" name="rowid" class="btn btn-primary" data-toggle="tooltip" data-placement="right" title="<?= $this->translate('Add suggestion') ?>"><span class="fa fa-plus"></span></button>
                                        &nbsp;
*/ ?>
                                    <a class="btn btn-info btn-sm" data-toggle="tooltip" data-placement="right" title="<?= $this->translate('See Details') ?>" href="<?= $detailUrl ?>"><span class="fa fa-search"></span></a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </table>
<?php /*
                    <button type="submit" value="all" name="rowid" class="btn btn-info"><?= $this->translate('Submit all') ?></button>
*/ ?>
                </form>
            </div>
        </div>

        <nav class="mt-4">
            <?= $this->paginationControl(
                    $this->translations,
                    'sliding',
                    'partial/paginator.phtml',
                    [
                        'route' => 'home',
                        'query' => [
                            'locale'  => $currentLocale,
                            'file'    => $currentFile,
                            'unclear' => $currentFilterUnclear,
                            'epp'     => $currentEPP,
                        ],
                    ]
                );
            ?>
        </nav>
    </div>
</div>

<?php $this->inlineScript()->captureStart(); ?>

$("document").ready(function () {
    $('#inputGroupLocaleSelect, #inputGroupFileSelect, #inputGroupPageSelect').change(function () {
        var url = "<?= $this->url('home') ?>?";

        url += "locale=" + $('#inputGroupLocaleSelect').val() + "&";
        url += "file=" + $('#inputGroupFileSelect').val() + "&";
        url += "epp=" + $('#inputGroupPageSelect').val() + "&";
        url += "unclear=<?= $currentFilterUnclear ?>&";

        window.location.href = url;
    });
});

<?php $this->inlineScript()->captureEnd(); ?>

<script>
    <?php if ($jumpToRow): ?>
        $(document).ready(function () {
            // if some suggestion is saved, jump to the row in the grid to be in focus to the next data set
            $('html, body').animate({
                scrollTop: $("#<?= $jumpToRow ?>").offset().top - $("#navbar").outerHeight()
            }, 1000);
        });
    <?php endif; ?>

    // toggle unclear translation flag
    function toggleUnclearTranslation(toggleButton) {
        var translationId = toggleButton.data("translation-id");
        $.ajax({
            type: "POST",
            url: "<?= $this->url('ajax', [ 'action' => 'toggle_unclear' ]); ?>",
            data: {"translation_id": translationId},
            success: function(data) {
                if (false == data.success) {
                    alert("An error occurred toggling the unclear status of element " + translationId + ":\n" + data.error);
                    return;
                }

                // change status in frontend
                if (false == data.new_state) {
                    toggleButton.attr("title", "clear translation at the moment");
                    toggleButton.html("<i class=\"fa fa-check-circle clear\"></i>");
                } else {
                    toggleButton.attr("title", "unclear translation at the moment");
                    toggleButton.html("<i class=\"fa fa-exclamation-triangle unclear\"></i>");
                }
            },
            error: function() {
                alert("An error occurred toggling the unclear translation status");
            }
        });
    }
</script>
