<?php
/**
 * @var $this Zend\View\Renderer\PhpRenderer
 *
 * @var \Application\ResultSet\SupportedLocale $supportedLocales
 * @var \Application\ResultSet\Translation     $translations
 * @var \Application\ResultSet\TranslationBase $translationBase
 * @var \Application\ResultSet\TranslationFile $translationFiles
 * @var int $translationsCount
 * @var string $currentLocale
 * @var string[] $currentFile
 * @var bool $currentFilterUnclear
 * @var int $currentPage
 * @var int $currentEPP - entries per page
 * @var int $maxPages
 * @var string[] messages with index messageLevel
 * @var string $jumpToRow
 */
?>

<?php if (isset($messages) && count($messages)): ?>
    <ul class="messages row">
        <?php foreach ($messages as $messageLevel => $messageLevelContainer): ?>
            <?php foreach ($messageLevelContainer as $message): ?>
                <li class="alert alert-<?php echo $this->escapeHtmlAttr($messageLevel); ?>" role="alert">
                    <?php echo $this->escapeHtml($message); ?>
                </li>
            <?php endforeach; ?>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>

<div class="row">
    <div class="card filter-area mt-4">
        <div class="card-header"><strong><?php echo $this->translate('Filter') ?></strong></div>
        <div class="card-body">

            <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    <?php echo $this->translate('Translation file') ?> <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="<?php echo $this->url('home', [], [ 'query' => [ 'locale' => $currentLocale, 'file' => null, 'filter_unclear_translation' => $currentFilterUnclear ] ]); ?>"><?php echo $this->translate('all files') ?></a></li>
                    <?php foreach ($translationFiles as $translationFile): ?>
                        <li><a href="<?php echo $this->url('home', [], [ 'query' => [ 'locale' => $currentLocale, 'file' => $translationFile->getFilename(), 'filter_unclear_translation' => $currentFilterUnclear ] ]); ?>">
                            <?php echo $translationFile->getFilename() ?></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>

            <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    <?php echo $this->translate('Language') ?> <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <?php foreach ($supportedLocales as $locale): ?>
                        <li><a href="<?php echo $this->url('home', [], [ 'query' => [ 'locale' => $locale->getLocale(), 'file' => $currentFile, 'filter_unclear_translation' => $currentFilterUnclear ] ]); ?>">
                            <?php echo $locale->getLocale() ?></a>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <strong><?php echo $this->translate('selected file:') ?></strong>
            <?php if (empty($currentFile)): ?>
                <span class="label label-info"><?php echo $this->translate('all files') ?></span>
            <?php else: ?>
                <?php foreach ($currentFile as $fileName): ?>
                    <span class="label label-primary"><?php echo $fileName ?></span>
                <?php endforeach; ?>
            <?php endif; ?>

            <strong><?php echo $this->translate('selected language:') ?></strong> <span class="label label-default"><?php echo $currentLocale ?></span>
            <strong><?php echo $this->translate('unclear translations:') ?> </strong>
            <?php if ($currentFilterUnclear): ?>
                <button class="btn btn-primary" onclick="location.href='<?php echo $this->url('home', [], [ 'query' => [ 'locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => 0 ] ]) ?>'">
                    <?php echo $this->translate('show only unclear') ?>
                </button>
            <?php else: ?>
                <button class="btn btn-default" onclick="location.href='<?php echo $this->url('home', [], [ 'query' => [ 'locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => 1 ] ]) ?>'">
                    <?php echo $this->translate('show only unclear') ?>
                </button>
            <?php endif; ?>

            <br />

            <ul class="pagination">
                <?php if ($currentPage > 1): ?>
                    <li><a href="<?php echo $this->url('home', [], [ 'query' => [ 'locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => $currentFilterUnclear, 'page' => $currentPage - 1, 'epp' => $currentEPP ] ]); ?>" aria-label="Previous">
                        &laquo;
                    </a></li>
                <?php endif; ?>
                <?php for ($i = 1; $i <= $maxPages; $i++): ?>
                    <?php $class = ($i == $currentPage) ? 'active' : ''; ?>
                    <li class="<?php echo $class ?>"><a href="<?php echo $this->url('home', [], [ 'query' => [ 'locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => $currentFilterUnclear, 'page' => $i, 'epp' => $currentEPP ] ]); ?>">
                        <?php echo $i ?>
                    </a></li>
                <?php endfor; ?>
                <?php if ($currentPage < $maxPages): ?>
                    <li><a href="<?php echo $this->url('home', [], [ 'query' => [ 'locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => $currentFilterUnclear, 'page' => $currentPage + 1, 'epp' => $currentEPP ] ]); ?>" aria-label="Next">
                        &raquo;
                    </a></li>
                <?php endif; ?>
            </ul>

            <span id="entries-per-page-button" style="margin-left: 10px"><!-- TODO: where comes the top margin from (see CSS)? -->
                <div class="btn-group">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                        <?php echo $this->translate('Entries per page') ?> <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="<?php echo $this->url('home', [], [ 'query' => [ 'locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => $currentFilterUnclear, 'page' => $currentPage, 'epp' => 25 ] ]); ?>">
                            25
                        </a></li>
                        <li><a href="<?php echo $this->url('home', [], [ 'query' => [ 'locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => $currentFilterUnclear, 'page' => $currentPage, 'epp' => 50 ] ]); ?>">
                            50
                        </a></li>
                        <li><a href="<?php echo $this->url('home', [], [ 'query' => [ 'locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => $currentFilterUnclear, 'page' => $currentPage, 'epp' => 100 ] ]); ?>">
                            100
                        </a></li>
                        <li><a href="<?php echo $this->url('home', [], [ 'query' => [ 'locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => $currentFilterUnclear, 'page' => $currentPage, 'epp' => 250 ] ]); ?>">
                            250
                        </a></li>
                        <li><a href="<?php echo $this->url('home', [], [ 'query' => [ 'locale' => $currentLocale, 'file' => $currentFile, 'filter_unclear_translation' => $currentFilterUnclear, 'page' => $currentPage, 'epp' => 'all' ] ]); ?>">
                            <?php echo $this->translate('all' ) ?>
                        </a></li>
                    </ul>
                </div>
                <strong><?php echo $this->translate('per page:') ?> </strong><span class="label label-default"><?php echo (null !== $currentEPP) ? (int)$currentEPP : $this->translate('all') ?></span>
            </span>
        </div>
    </div>

    <div class="card mt-4">
        <div class="card-header"><strong><?php echo $this->translate('overall view list') ?></strong> (<?php echo count($translations) ?> / <?php echo (int)$translationsCount ?> <?php echo $this->translate('elements') ?>)</div>
        <div class="card-body">
            <form action="" method="post">
                <input type="hidden" name="translation_locale" value="<?php echo $this->escapeHtmlAttr($currentLocale) ?>" />
                <table class="table table-hover" id="translation-grid">
                    <tr>
                        <th><?php echo $this->translate('ID') ?></th>
                        <th><?php echo $this->translate('Origin source') ?></th>
                        <th><?php echo $this->translate('Current translation') ?></th>
                        <th><span title="<?php echo $this->translate('unclear translation') ?>"><?php echo $this->translate('Status') ?></span></th>
                        <th><?php echo $this->translate('New suggested translation') ?></th>
                        <th></th>
                    </tr>
                    <?php foreach ($translations as $translation): ?>
                        <?php $base = $translationBase->getById($translation->getBaseId()) ?>
                        <?php $rowName = 'row' . $translation->getBaseId(); ?>
                        <tr id="<?php echo $rowName ?>">
                            <td><?php echo $translation->getBaseId() ?></td>
                            <td>
                                <?php if ($base): ?>
                                    <?php echo $this->escapeHtml($base->getOriginSource()) ?>
                                <?php endif; ?>
                            </td>
                            <td><?php echo $this->escapeHtml($translation->getCurrentTranslation()) ?></td>
                            <td class="text-center">
                                <?php if ($translation->getUnclearTranslation()): ?>
                                    <button class="unclear-translation" title="<?php echo $this->translate('unclear translation at the moment') ?>" type="button"
                                            onclick="toggleUnclearTranslation($(this))" data-translation-id="<?php echo $this->escapeHtmlAttr($translation->getTranslationId())?>">
                                        <i class="glyphicon glyphicon-exclamation-sign unclear"></i>
                                    </button>
                                <?php else: ?>
                                    <button class="unclear-translation" title="<?php echo $this->translate('clear translation at the moment') ?>" type="button"
                                            onclick="toggleUnclearTranslation($(this))" data-translation-id="<?php echo $this->escapeHtmlAttr($translation->getTranslationId())?>">
                                        <i class="glyphicon glyphicon-ok-circle clear"></i>
                                    </button>
                                <?php endif; ?>
                            </td>
                            <td class="suggested-translation">
                                <input type="text" class="form-control" name="<?php echo $rowName?>_suggestedTranslation" value="" />
                            </td>
                            <td>
                                <div style="min-width: 125px">
                                    <input type="hidden" name="<?php echo $rowName?>_baseId" value="<?php echo $this->escapeHtmlAttr($translation->getBaseId())?>" />
                                    <input type="hidden" name="<?php echo $rowName?>_translationId" value="<?php echo $this->escapeHtmlAttr($translation->getTranslationId())?>" />
                                    <button type="submit" value="<?php echo $rowName?>" name="rowid" class="btn btn-primary btn-lg" data-toggle="tooltip" data-placement="right" title="<?php echo $this->translate('Add suggestion') ?>"><span class="glyphicon glyphicon-plus"></span></button>
                                    &nbsp;
                                    <a class="btn btn-default btn-lg" data-toggle="tooltip" data-placement="right" title="<?php echo $this->translate('See Details') ?>" href="<?php echo $this->url('index', [ 'action' => 'edit', 'base_id' => $translation->getBaseId() ], [ 'query' => [ 'locale' => $currentLocale ] ]) ?>"><span class="glyphicon glyphicon-search"></span></a>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>

                </table>
                <button type="submit" value="all" name="rowid" class="btn btn-primary"><?php echo $this->translate('Submit all') ?></button>
            </form>
        </div>
    </div>

</div>
<script>
    <?php if ($jumpToRow): ?>
        $(document).ready(function () {
            // if some suggestion is saved, jump to the row in the grid to be in focus to the next data set
            $('html, body').animate({
                scrollTop: $("#<?php echo $jumpToRow ?>").offset().top - $("#navbar").outerHeight()
            }, 1000);
        });
    <?php endif; ?>

    // toggle unclear translation flag
    function toggleUnclearTranslation(toggleButton) {
        var translationId = toggleButton.data("translation-id");
        $.ajax({
            type: "POST",
            url: "<?php echo $this->url('ajax', [ 'action' => 'toggle_unclear' ]); ?>",
            data: {"translation_id": translationId},
            success: function(data) {
                if (false == data.success) {
                    alert("An error occurred toggling the unclear status of element " + translationId + ":\n" + data.error);
                    return;
                }

                // change status in frontend
                if (false == data.new_state) {
                    toggleButton.attr("title", "clear translation at the moment");
                    toggleButton.html("<i class=\"glyphicon glyphicon-ok-circle clear\"></i>");
                } else {
                    toggleButton.attr("title", "unclear translation at the moment");
                    toggleButton.html("<i class=\"glyphicon glyphicon-exclamation-sign unclear\"></i>");
                }
            },
            error: function() {
                alert("An error occurred toggling the unclear translation status");
            }
        });
    }
</script>
