<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Zend\View\Model\ViewModel      $viewModel
 * @var \Export\Form\ExportForm         $form
 */

$title = $this->translate('Download CSV file(s)');
$this->headTitle($title);
?>

<?php if (count($downloadFiles)): ?>
    <form action="<?= $this->url('export', [ 'action' => 'compress' ]) ?>" method="post">
        <div class="card">
            <div class="card-header">
                <?= $this->translate('Please download the following files'); ?>
            </div>
            <div class="card-body">
                <table class="table table-hover">
                    <thead>
                        <th scope="col" width="1%">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" name="selectAll" id="selectAll" value="1" title="<?= $this->translate('Select all') ?>">
                                <label class="form-check-label" for="selectAll"></label>
                            </div>
                        </th>
                        <th scope="col"><?= $this->translate('File') ?></th>
                        <th scope="col"><?= $this->translate('Locale') ?></th>
                    </thead>
                    <tbody>
                        <?php foreach ($downloadFiles as $file): ?>
                            <?php $id = $file['locale'] . '_' . $file['filename']; ?>
                            <tr>
                                <td>
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="download[<?php $file['locale'] ?>]" id="download_<?= $this->escapeHtmlAttr($id) ?>" value="<?= $this->escapeHtmlAttr($file['filename']) ?>">
                                        <label class="form-check-label" for="download_<?= $this->escapeHtmlAttr($id) ?>"></label>
                                    </div>
                                </td>
                                <td>
                                    <a href="<?= $this->url('export', [ 'action' => 'download'], [ 'query' => [ 'locale' => $file['locale'],  'file' => $file['filename'] ] ]) ?>"><?= $this->escapeHtml($file['filename']) ?></a>
                                </td>
                                <td>
                                    <?= $this->flag($file['locale']) ?>
                                    <?= $this->translate($file['locale']) ?>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>

                <button type="submit" value="single" name="rowid" class="btn btn-success pull-right" id="downloadAllButton">
                    <?= $this->translate('Download all selected as zip') ?>
                </button>
            </div>
        </div>
    </form>
<?php endif; ?>

<?php $this->inlineScript()->captureStart(); ?>

$("document").ready(function () {
    // Toggle all checkboxes
    $(':checkbox[name="selectAll"]').click (function () {
        $(':checkbox[name="download[]"]').prop('checked', this.checked);
    });
});

<?php $this->inlineScript()->captureEnd(); ?>
